behaviors:

  F1TENTH_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3e-4
      beta: 0.001
      epsilon: 0.2
      lambd: 0.98
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
      gail:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        demo_path: C:\Users\tsamak\Desktop\AutoDRIVE Simulator\Assets\ML Resources\Demonstrations\F1TENTH1.demo
    behavioral_cloning:
      demo_path: C:\Users\tsamak\Desktop\AutoDRIVE Simulator\Assets\ML Resources\Demonstrations\F1TENTH1.demo
      strength: 0.5
      steps: 0
    keep_checkpoints: 5
    max_steps: 1e6
    time_horizon: 128
    summary_freq: 50000

  F1TENTH_2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3e-4
      beta: 0.001
      epsilon: 0.2
      lambd: 0.98
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
      gail:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        demo_path: C:\Users\tsamak\Desktop\AutoDRIVE Simulator\Assets\ML Resources\Demonstrations\F1TENTH2.demo
    behavioral_cloning:
      demo_path: C:\Users\tsamak\Desktop\AutoDRIVE Simulator\Assets\ML Resources\Demonstrations\F1TENTH2.demo
      strength: 0.5
      steps: 0
    keep_checkpoints: 5
    max_steps: 1e6
    time_horizon: 128
    summary_freq: 50000